name: Debugging with SSH
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Try Download
        run: |
            cd /home/runner/
            mkdir artifact
            cd artifact
            mkdir files
            cd files
            rm -rf ./*
            pip install gdown
            gdown 1okbCy6uwtTj_zwr6igB2NGexzcV7MNIV
            gdown 1b2-NzBDA-6-dVmshixmMRWotRQ_pDXO8
#            gdown 1aeiQIQcehemiTse_6vAmItqtMKh2os6w
#            gdown 1gc3y-iyCLO7Jk0Z8Aqmcs0K22alj3DYS
#            gdown 1s4wr7RKERtuX76XL2wE-YkmtZSv7VdB3
#            gdown 1zGsRI4XlPa9aS46KpQoa-Cvecq40Ccvl
            
            
            
#       - name: Start SSH via Ngrok
#         if: ${{ failure() }}
#         run: curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
#         env:
#           # After sign up on the https://ngrok.com/
#           # You can find this token here: https://dashboard.ngrok.com/get-started/setup
#           NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
#           # This password you will use when authorizing via SSH
#           USER_PASS: ${{ secrets.USER_PASS }}
          
      - name: Upload files
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Files
          path: /home/runner/artifact/files/
