name: Debugging with SSH
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

       
    # You might want to Checkout your repo first, but not mandatory
      - name: Check Out
        uses: actions/checkout@v3
    # Cleanup The Actions Workspace Using Custom Composite Run Actions
      - name: Cleanup
        uses: rokibhasansagar/slimhub_actions@main
      # That's it! Now use your normal steps
      - name: Setup Python
        uses: actions/setup-python@v3.1.4
        with:
          python-version: 2.7
          
      - name: Prepare the environment
        run: |
          sudo apt update
          sudo add-apt-repository universe
          sudo apt-get install fakeroot dpkg-dev libcurl4-openssl-dev python3 repo python3-pip
          sudo apt-get install aptitude -y
          sudo aptitude install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
          sudo aptitude install -y openjdk-8-jdk
          curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
          sudo python2 get-pip.py
          rm -f get-pip.py
          sudo pip2 install pycryptodome
          sudo pip3 install pycryptodome
          wget https://github.com/tickstep/aliyunpan/releases/download/v0.2.7/aliyunpan-v0.2.7-linux-amd64.zip
          unzip aliyunpan-v0.2.7-linux-amd64.zip
          aria2c -c -s 32 http://tool.bitefu.net/123pan/?url=gRZRVv-ij47 | tar zxvf source.tar.gz
          sudo rm source.tar.gz
          
          
      - name: Start SSH via Ngrok（Prepare Failed）
        if: ${{ failure() }}
        run: curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
        env:
          # After sign up on the https://ngrok.com/
          # You can find this token here: https://dashboard.ngrok.com/get-started/setup
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          # This password you will use when authorizing via SSH
          USER_PASS: ${{ secrets.USER_PASS }}
      
      - name: sleep for 20 mins（Prepare Failed）
        if: ${{ failure() }}
        run: sleep 20m
        
      - name: Compile Android
        run: |
          cd source
          cd vendor/sprd/release/IDH/Script/
          sudo ./build_pac.sh -a ud710_2h10_native-userdebug-native -b all
      
      - name: Start SSH via Ngrok（Build Success and I will upload the packages into the aliyundrive）
#        if: ${{ failure() }}
        run: curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
        env:
          # After sign up on the https://ngrok.com/
          # You can find this token here: https://dashboard.ngrok.com/get-started/setup
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          # This password you will use when authorizing via SSH
          USER_PASS: ${{ secrets.USER_PASS }}
      
      - name: Sleep for 20min（Build Success and I will upload the packages into the aliyundrive）
#        if: ${{ failure() }}
        run: sleep 30m


      - name: Start SSH via Ngrok（Compile Failed）
        if: ${{ failure() }}
        run: curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
        env:
          # After sign up on the https://ngrok.com/
          # You can find this token here: https://dashboard.ngrok.com/get-started/setup
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          # This password you will use when authorizing via SSH
          USER_PASS: ${{ secrets.USER_PASS }}
        
      - name: sleep for 20 mins（Compile Failed）
        if: ${{ failure() }}
        run: sleep 2h
